spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fixora_notifications_db
    username: xxxxxx
    password: xxxxxx
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

    test-connection: false

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  mail:
    from: ${MAIL_FROM:${MAIL_USERNAME}}

server:
  port: 8086
  servlet:
    context-path: /api/v1/

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_TOKEN_EXPIRE_TIME}
