spring:
  application:
    name: ai-service
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8089
  servlet:
    context-path: /api/v1/

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_TOKEN_EXPIRE_TIME}

gemini:
  base-url: https://generativelanguage.googleapis.com
  api-key: ${GEMINI_API_KEY}
  model: gemini-3.1-flash-lite
  connect-timeout: 7s
  read-timeout: 45s
  max-output-tokens: 2000
  temperature: 0.2
